package de.triona.console;

import java.io.File;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import static javax.swing.JOptionPane.*;

/**
 * Setting the options
 *
 * @author Bernhard
 */
public class OptionsFrame extends javax.swing.JFrame {

    private static final Logger logger = Logger.getLogger(OptionsFrame.class.getName());

    public OptionsFrame() {
        initComponents();
        txtDir.setText(ConsoleFrame.SERVER_DIR);
        txtStart.setText(ConsoleFrame.START_COMMAND);
        txtStop.setText(ConsoleFrame.STOP_COMMAND);
        txtPkg.setText(ConsoleFrame.OWN_PKG);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tabbedPane = new javax.swing.JTabbedPane();
        pnlOptions = new javax.swing.JPanel();
        lblDir = new javax.swing.JLabel();
        txtDir = new javax.swing.JTextField();
        lblStart = new javax.swing.JLabel();
        txtStart = new javax.swing.JTextField();
        lblStop = new javax.swing.JLabel();
        txtStop = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        pnlFormat = new javax.swing.JPanel();
        lblPkg = new javax.swing.JLabel();
        txtPkg = new javax.swing.JTextField();
        btnCancel1 = new javax.swing.JButton();
        btnSave1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Einstellungen");
        setPreferredSize(new java.awt.Dimension(350, 180));

        pnlOptions.setLayout(new java.awt.GridBagLayout());

        lblDir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDir.setText("Verzeichnis");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 0);
        pnlOptions.add(lblDir, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 3, 0);
        pnlOptions.add(txtDir, gridBagConstraints);

        lblStart.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblStart.setText("Starte Server");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 0);
        pnlOptions.add(lblStart, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 3, 0);
        pnlOptions.add(txtStart, gridBagConstraints);

        lblStop.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblStop.setText("Stoppe Server");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 0);
        pnlOptions.add(lblStop, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 3, 0);
        pnlOptions.add(txtStop, gridBagConstraints);

        btnCancel.setText("Abbrechen");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        pnlOptions.add(btnCancel, gridBagConstraints);

        btnSave.setText("Speichern");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        pnlOptions.add(btnSave, gridBagConstraints);

        tabbedPane.addTab("Server Settings", pnlOptions);

        pnlFormat.setLayout(new java.awt.GridBagLayout());

        lblPkg.setText("Your package name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 0);
        pnlFormat.add(lblPkg, gridBagConstraints);

        txtPkg.setToolTipText("e.g. org.yourname.project");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 3, 0);
        pnlFormat.add(txtPkg, gridBagConstraints);

        btnCancel1.setText("Abbrechen");
        btnCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        pnlFormat.add(btnCancel1, gridBagConstraints);

        btnSave1.setText("Speichern");
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        pnlFormat.add(btnSave1, gridBagConstraints);

        tabbedPane.addTab("Formatting", pnlFormat);

        getContentPane().add(tabbedPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        System.out.println("Abbruch");
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        System.out.println("Speichern");

        if (validateServerSettings(txtDir.getText(), txtStart.getText(), txtStop.getText(), txtPkg.getText())) {
            ConsoleFrame.SERVER_DIR = txtDir.getText();
            ConsoleFrame.START_COMMAND = txtStart.getText();
            ConsoleFrame.STOP_COMMAND = txtStop.getText();
            ConsoleFrame.OWN_PKG = txtPkg.getText();
            dispose();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    public boolean validateServerSettings(String serverDir, String startCmd, String stopCmd, String ownPkg) {
        // Check if the server directory exists
        String errorTitle = "ERROR in Server Settings";
        if (!new File(serverDir).exists()) {
            String msg = serverDir + " doesn't exist. It should be sth. like C:/jboss7/";
            JOptionPane.showMessageDialog(this, msg, errorTitle, ERROR_MESSAGE);
            return false;
        }
        // Check Server start command
        String startCommand = serverDir + startCmd;
        if (startCommand.contains(" ")) {
            startCommand = startCommand.substring(0, startCommand.indexOf(' '));
            logger.info("StartCommand without extension='" + startCommand + "'");
        }
        if (!new File(startCommand).exists()) {
            String msg = startCmd + " doesn't exist. It should be sth. like standalone.xml";
            JOptionPane.showMessageDialog(this, msg, errorTitle, ERROR_MESSAGE);
            return false;
        }
        // Check Server stop command
        String stopCommand = serverDir + stopCmd;
        if (stopCommand.contains(" ")) {
            stopCommand = stopCommand.substring(0, stopCommand.indexOf(' '));
            logger.info("StopCommand without extension='" + stopCommand + "'");
        }
        if (!new File(stopCommand).exists()) {
            String msg = stopCmd + " doesn't exist. It should be sth. like jboss-cli.bat";
            JOptionPane.showMessageDialog(this, msg, errorTitle, ERROR_MESSAGE);
            return false;
        }
        // Check package name
        String regex = "[a-z\\.]{1,}";
        if (!Pattern.matches(regex, ownPkg)) {
            String msg = ownPkg + " is not a valid package name. It should be sth. de.mycompany.proj";
            JOptionPane.showMessageDialog(this, msg, errorTitle, ERROR_MESSAGE);
            return false;
        }

        return true;
    }

    private void btnCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel1ActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancel1ActionPerformed

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
        if (txtPkg.getText().isEmpty()) {
            String msg = "Do you really want to leave the package name empty?\n";
            msg += "There will be no highlighting of your package in the console";
            int res = JOptionPane.showConfirmDialog(this, msg, "WARNING", WARNING_MESSAGE);
            if (res == NO_OPTION || res == CANCEL_OPTION) {
                return;
            }
        }
        ConsoleFrame.OWN_PKG = txtPkg.getText();
        dispose();
    }//GEN-LAST:event_btnSave1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            logger.severe(ex.getMessage());
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new OptionsFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancel1;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSave1;
    private javax.swing.JLabel lblDir;
    private javax.swing.JLabel lblPkg;
    private javax.swing.JLabel lblStart;
    private javax.swing.JLabel lblStop;
    private javax.swing.JPanel pnlFormat;
    private javax.swing.JPanel pnlOptions;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextField txtDir;
    private javax.swing.JTextField txtPkg;
    private javax.swing.JTextField txtStart;
    private javax.swing.JTextField txtStop;
    // End of variables declaration//GEN-END:variables
}
